### PR TITLE
Cpp update

### PR DESCRIPTION
**Pull request by mislavn**
With this path a C++ memory leak is fixed that @jktjkt reported.
The discussion is at: https://github.com/sysrepo/sysrepo/issues/581

In the following pull requests I will separate Val/Vals and Tree/Trees class into two parts. One immutable and  one mutable (for setting values).

### CODE REVIEW

**Comment by rastislavszabo** [comment]
@jktjkt Could you please review this?

**Comment by rastislavszabo** [comment]
Hi Mislav,
please see the Travis builds of your PR, there are some issue with python tests, e.g.:

```
52/58 Test #52: python_SysrepoBasicTest ..........***Failed    0.22 sec

...E...E..

======================================================================

ERROR: test_get_items (__main__.SysrepoBasicTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/sysrepo/sysrepo/build/swig/python2/tests/SysrepoBasicTest.py", line 99, in test_get_items

    self.assertRegexpMatches(v.xpath(), "/test-module:main*")

AttributeError: 'NoneType' object has no attribute 'xpath'

======================================================================

ERROR: test_move_item (__main__.SysrepoBasicTest)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/sysrepo/sysrepo/build/swig/python2/tests/SysrepoBasicTest.py", line 140, in test_move_item

    self.assertEqual(items.val(i).xpath(), lists[i])

AttributeError: 'NoneType' object has no attribute 'xpath'

----------------------------------------------------------------------

Ran 10 tests in 0.179s

FAILED (errors=2)

/test-module:main/i32  = 32

swig/python detected a memory leak of type 'Logs *', no destructor found.
```

**Comment by mislavn** [comment]
> Hi @mislavn
> please see the Travis builds of your PR, there are some issue with python tests, e.g.:

I am working on that.

**Comment by jktjkt** [comment]
The code looks good (the leaks are gone now), but my application now segfaults in ``Val::xpath``. Here's how the code looks like:

```C++
auto vals = session->get_items((modulePrefix + ":amplifier/stage-1/sensors/*").c_str());
REQUIRE(!!vals);
for (size_t i = 0; i < vals->val_cnt(); ++i) {
    const auto &val = vals->val(i);
    std::cout << val->xpath() << ": " << val->type() << std::endl;
}
```

**Comment by mislavn** [comment]
Thanks @jktjkt for the example.

**Comment by jktjkt** [comment]
...and it doesn't appear to segfault all the time, but still in a substantial number of cases. Not nice, trying to dig deeper.

**Comment by jktjkt** [comment]
I've uploaded my fixes to https://github.com/jktjkt/sysrepo/commits/fix-cpp-635 . I don't think that GitHub allows me as a mere contributor to update this pull request because it belongs to someone else.

**Comment by mislavn** [comment]
@jktjkt I will rebase your branch onto my.

**Comment by mislavn** [comment]
@jktjkt should I apply similar logic to other parts of the C++ code base?

**Comment by jktjkt** [comment]
> @jktjkt should I apply similar logic to other parts of the C++ code base?

Yes, I think that going with idiomatic C++ is reasonable in the long term, but I will prefer to have this merged before the code gets cleaned up in future.

**Comment by mislavn** [comment]
> Yes, I think that going with idiomatic C++ is reasonable in the long term, but I will prefer to have this merged before the code gets cleaned up in future.

@jktjkt OK, I will create a new pull request with the proposed changes once this one is merged.

**Comment by jktjkt** [comment]
(You might want to reopen this one.)

**Comment by mislavn** [comment]
Sorry, misclicked.

**Pull request merged**
