### PR TITLE
Refactoring of C++'s logging with one SR change

### PR DESCRIPTION
**Pull request by jktjkt**
This series:
- switches the C++ code to static methods (please read the commit messages),
- adds logging callbacks for C++,
- changes core SR to not skip expensive computation when a custom CB is active (see the last commit).

I have no idea whether you want the last commit or not; please feel free to remove that one.

Ccing @mislavn for the C++ part.

### CODE REVIEW

**Comment by mislavn** [comment]
I will check why swig breaks it this pull request.

**Comment by mislavn** [comment]
@jktjkt swig doesn't have out-of-the-box support for std::function so i would need to add custom code for all of the target languages.

An easier solution would be to add a virtual functions and custom wrapper code for Python and Lua, just like in the Callback class.

@jktjkt  will this be a problem for you?

If you want the C++ bindings could keep the std::function but Java, Python and Lua will use the virtual functions.

**Comment by jktjkt** [comment]
> I will check why swig breaks it this pull request.

Sorry for confusion -- this patch series does not break stuff; one needs to nuke the build dir so that the build system regenerates the relevant SWIG intermediate files.

> swig doesn't have out-of-the-box support for std::function

Yes :(. I prefer to have C++ bindings using native C++ idioms; if you would like to, I can provide an extra wrapper using virtual methods on top of that for use by SWIG's target languages.

**Comment by jktjkt** [comment]
I see that Travis builds fail; I'm using SWIG Version 3.0.5 locally.

**Comment by mislavn** [comment]
> Yes :(. I prefer to have C++ bindings using native C++ idioms; if you would like to, I can provide an extra wrapper using virtual methods on top of that for use by SWIG's target languages.

That would be great.

> I see that Travis builds fail; I'm using SWIG Version 3.0.5 locally.
OK, I will check this.

**Comment by mislavn** [comment]
@rastislavszabo can you change the swig version on the build server.

I will check now what is the minimum swig version required for successful build of the language bindings.

**Comment by mislavn** [comment]
@jktjkt I can not build this locally without ignoring some methods in the Logs class.
Did you locally built swig bindings for python or lua, it breaks only on them.

**Comment by rastislavszabo** [comment]
@mislavn 
> can you change the swig version on the build server

If it's really needed, you can change it here:
https://github.com/sysrepo/sysrepo/blob/master/deploy/travis/install-libs.sh
and here:
https://github.com/sysrepo/sysrepo/blob/master/deploy/travis/install-libs-osx.sh

**Comment by jktjkt** [comment]
> I can not build this locally without ignoring some methods in the Logs class.

Clean build fails for me, too, so I made these methods only available when doing C++ stuff. Is this OK-ish for you? An alternative is to simply kill this feature for now; the other commits are IMHO still valuable. And yes, I'm OK with adding a virtual-method-based interface, but I'd prefer to wait until I finish legal paperwork locally (which means that I cannot give any ETA).

**Comment by mislavn** [comment]
> Is this OK-ish for you? An alternative is to simply kill this feature for now; the other commits are IMHO still valuable. And yes, I'm OK with adding a virtual-method-based interface, but I'd prefer to wait until I finish legal paperwork locally (which means that I cannot give any ETA).

I can add a small patch to swig to ignore some methods from the Logs class, it will compile then.
I will send you the patch once I am finished with the issue:

https://github.com/sysrepo/sysrepo/issues/379

**Comment by mislavn** [comment]
@jktjkt  can you add the line:

 %ignore Logs;

in the file swig/swig_base/cpp_classes.i anywhere after the 30-th line.

Then it should compile. When you are finished with the class and add the virtual functions I will make it compile with swig.

**Comment by rastislavszabo** [comment]
@mislavn , @jktjkt What about this pull request? It hasn't been touched for 2 weeks and its build is still failing in Travis. How can we merge it / should we close it?

**Comment by rastislavszabo** [comment]
Guys, it seems that this pull request cannot be merged and no one knows how to fix it. Please open a new one (or ones) if you need any changes in this PR.

**Pull request closed without merging**
