### PR TITLE
sysrepocfg: fixed memleaks and minor performance optimization

### PR DESCRIPTION
**Pull request by jktjkt**
- simplify the `sysrepocfg --set ... --set-val ...`
- remove duplicate validation in `sysrepocfg`

cc: #892 , but it doesn't really fix the underlying problem

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi,
thanks, seems fine, all that is probably needed is to fix `sysrepocfg.c:1049:9: error: unused variable ‘ret’`.

Regards,
Michal

**Comment by jktjkt** [comment]
Ah, I missed that. Squashed a fix in there, and added a follow-up cleanup of an unused variable.

**Comment by michalvasko** [comment]
Hi,
so it seems you have broken something and sysrepocfg tests `srcfg_test_xpath` and `srcfg_test_merge` did not pass. It would be great if you could fix it yourself, otherwise I will look at it once I find the time.

Regards,
Michal

**Comment by jktjkt** [comment]
That's a... mess. These tests contain hardcoded /tmp locations and rely on being run from a subdirectory of the build dir. They use a shell script in place of $EDITOR. The actual output is not printed anywhere, just compared against the expected error messages. Etc.

Anyway, even 16914df fails due to memory leaks reported by ASAN -- perhaps in the child process:

```
$ LD_LIBRARY_PATH=/opt/nc/lib64 ctest -R sysrepocfg --output-on-failure
Test project /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug
    Start 29: sysrepocfg_test
1/1 Test #29: sysrepocfg_test ..................***Failed    4.43 sec
[==========] Running 8 test(s).
[ RUN      ] srcfg_test_version
[       OK ] srcfg_test_version
[ RUN      ] srcfg_test_help
[       OK ] srcfg_test_help
[ RUN      ] srcfg_test_export
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
[       OK ] srcfg_test_export
[ RUN      ] srcfg_test_editing
../src/sysrepocfg: Invalid datastore specified (select either "running" or "startup").
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
../src/sysrepocfg: Unsupported data format (xml and json are supported).
../src/sysrepocfg: Module name is not specified.
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.USgXNJ
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.diRXB5
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.lkFfAg
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.2ZgjzF
[ERR] (srcfg_import_datastore:795) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.2ZgjzF
[ERR] (srcfg_import_datastore:795) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()
+ '[' 1 -ne 1 ']'
+ cp sysrepocfg_test-new_config.txt /tmp/srcfg.test-module.startup.2ZgjzF
[ERR] (srcfg_import_datastore:795) Unable to parse the input data: Encountered invalid character sequence "user xmlns". ()

=================================================================
==18123==ERROR: LeakSanitizer: detected memory leaks

Indirect leak of 648 byte(s) in 9 object(s) allocated from:
    #0 0x7f250b950d40 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xd2d40)
    #1 0x7f250ad54e1a in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:886
    #2 0x7f250ad55e95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #3 0x7f250ad56b6b in lyxml_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1165
    #4 0x7f250ae501f7 in lyd_parse_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:416
    #5 0x7f250ae509ca in lyd_parse_data_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:484
    #6 0x7f250ae50d80 in lyd_parse_fd_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:521
    #7 0x7f250ae50f26 in lyd_parse_fd /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:535
    #8 0x40b972 in srcfg_import_datastore /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:786
    #9 0x413b5e in srcfg_edit_operation /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:1605
    #10 0x415aaa in main /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:2046
    #11 0x7f2509ef78b3 in __libc_start_main (/lib64/libc.so.6+0x208b3)
    #12 0x403008 in _start (/home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/src/sysrepocfg+0x403008)

Indirect leak of 648 byte(s) in 9 object(s) allocated from:
    #0 0x7f250b950d40 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xd2d40)
    #1 0x7f250ad54e1a in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:886
    #2 0x7f250ad56b6b in lyxml_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1165
    #3 0x7f250ae501f7 in lyd_parse_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:416
    #4 0x7f250ae509ca in lyd_parse_data_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:484
    #5 0x7f250ae50d80 in lyd_parse_fd_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:521
    #6 0x7f250ae50f26 in lyd_parse_fd /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:535
    #7 0x40b972 in srcfg_import_datastore /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:786
    #8 0x413b5e in srcfg_edit_operation /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:1605
    #9 0x415aaa in main /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:2046
    #10 0x7f2509ef78b3 in __libc_start_main (/lib64/libc.so.6+0x208b3)
    #11 0x403008 in _start (/home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/src/sysrepocfg+0x403008)

Indirect leak of 360 byte(s) in 9 object(s) allocated from:
    #0 0x7f250b950d40 in calloc (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xd2d40)
    #1 0x7f250ad53a19 in parse_attr /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:743
    #2 0x7f250ad562f0 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1066
    #3 0x7f250ad56b6b in lyxml_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1165
    #4 0x7f250ae501f7 in lyd_parse_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:416
    #5 0x7f250ae509ca in lyd_parse_data_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:484
    #6 0x7f250ae50d80 in lyd_parse_fd_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:521
    #7 0x7f250ae50f26 in lyd_parse_fd /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_data.c:535
    #8 0x40b972 in srcfg_import_datastore /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:786
    #9 0x413b5e in srcfg_edit_operation /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:1605
    #10 0x415aaa in main /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/src/executables/sysrepocfg.c:2046
    #11 0x7f2509ef78b3 in __libc_start_main (/lib64/libc.so.6+0x208b3)
    #12 0x403008 in _start (/home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/src/sysrepocfg+0x403008)

SUMMARY: AddressSanitizer: 1656 byte(s) leaked in 27 allocation(s).
[bt] #0 /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test(assert_int_equal_bt+0x40) [0x41de46]
        /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/helpers/system_helper.c:266
[bt] #1 /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test() [0x41e6dd]
        /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/helpers/system_helper.c:364
[bt] #2 /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test(exec_shell_command+0x24b) [0x41ec3f]
        /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/helpers/system_helper.c:446
[bt] #3 /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test() [0x424c74]
        /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:883
c:446
[bt] #4 /usr/lib64/libcmocka.so.0(+0x4d97) [0x7f1e9836fd97]
        ??:0
/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:883
c:446
[bt] #5 /usr/lib64/libcmocka.so.0(_cmocka_run_group_tests+0x308) [0x7f1e983704e8]
        ??:0
/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:883
c:446
[bt] #6 /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test(main+0x73d) [0x425f2e]
        /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:1298
:446
[bt] #7 /lib64/libc.so.6(__libc_start_main+0x114) [0x7f1e970e08b4]
        ??:0
/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:1298
:446
[bt] #8 /home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test(_start+0x29) [0x418909]
        ??:?
/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:1298
:446
0 != 0x1
/home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/helpers/system_helper.c:266: error: Failure!

REGEX: '(.*Unable to apply the changes.*){3}Your changes have been saved to 'sysrepocfg_test-dump.txt''
FILE: ''
[  FAILED  ] srcfg_test_editing
[ RUN      ] srcfg_test_editing
=================================================================
==17847==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7ffde46fd990 at pc 0x7f1e9751936e bp 0x7ffde46fd870 sp 0x7ffde46fd860
WRITE of size 1 at 0x7ffde46fd990 thread T0
    #0 0x7f1e9751936d in copyutf8 /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/parser.c:3687
    #1 0x7f1e974f950f in parse_text /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:687
    #2 0x7f1e974fc002 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1043
    #3 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #4 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #5 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #6 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #7 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #8 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #9 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #10 0x7f1e974fcb6b in lyxml_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1165
    #11 0x7f1e975541df in yin_read_module /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/parser_yin.c:7095
    #12 0x7f1e975d3160 in lys_parse_mem_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_schema.c:961
    #13 0x7f1e975d32d6 in lys_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_schema.c:991
    #14 0x7f1e974b0bff in ly_ctx_new /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/context.c:108
    #15 0x41bbc7 in createDataTreeIETFinterfacesModule /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/helpers/test_module_helper.c:404
    #16 0x421b78 in srcfg_test_set_running_datastore /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:227
    #17 0x7f1e9836fe45  (/usr/lib64/libcmocka.so.0+0x4e45)
    #18 0x7f1e983704b7 in _cmocka_run_group_tests (/usr/lib64/libcmocka.so.0+0x54b7)
    #19 0x425f2d in main /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:1298
    #20 0x7f1e970e08b3 in __libc_start_main (/lib64/libc.so.6+0x208b3)
    #21 0x418908 in _start (/home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test+0x418908)

Address 0x7ffde46fd990 is located in stack of thread T0==17847==AddressSanitizer CHECK failed: /var/tmp/portage/sys-devel/gcc-6.3.0/work/gcc-6.3.0/libsanitizer/asan/asan_thread.cc:243 "((ptr[0] == kCurrentStackFrameMagic)) != (0)" (0x0, 0x0)
    #0 0x7f1e98652436  (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xdd436)
    #1 0x7f1e9865a316 in __sanitizer::CheckFailed(char const*, int, char const*, unsigned long long, unsigned long long) (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xe5316)
    #2 0x7f1e98657771  (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xe2771)
    #3 0x7f1e9864d9a6  (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xd89a6)
    #4 0x7f1e9864dfc2  (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xd8fc2)
    #5 0x7f1e98651559  (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xdc559)
    #6 0x7f1e98652e28 in __asan_report_store1 (/usr/lib/gcc/x86_64-pc-linux-gnu/6.3.0/libasan.so.3+0xdde28)
    #7 0x7f1e9751936d in copyutf8 /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/parser.c:3687
    #8 0x7f1e974f950f in parse_text /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:687
    #9 0x7f1e974fc002 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1043
    #10 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #11 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #12 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #13 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #14 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #15 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #16 0x7f1e974fbe95 in lyxml_parse_elem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1027
    #17 0x7f1e974fcb6b in lyxml_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/xml.c:1165
    #18 0x7f1e975541df in yin_read_module /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/parser_yin.c:7095
    #19 0x7f1e975d3160 in lys_parse_mem_ /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_schema.c:961
    #20 0x7f1e975d32d6 in lys_parse_mem /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/tree_schema.c:991
    #21 0x7f1e974b0bff in ly_ctx_new /home/jkt/work/cesnet/gerrit/github/CESNET/libyang/src/context.c:108
    #22 0x41bbc7 in createDataTreeIETFinterfacesModule /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/helpers/test_module_helper.c:404
    #23 0x421b78 in srcfg_test_set_running_datastore /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:227
    #24 0x7f1e9836fe45  (/usr/lib64/libcmocka.so.0+0x4e45)
    #25 0x7f1e983704b7 in _cmocka_run_group_tests (/usr/lib64/libcmocka.so.0+0x54b7)
    #26 0x425f2d in main /home/jkt/work/cesnet/gerrit/github/sysrepo/sysrepo/tests/sysrepocfg_test.c:1298
    #27 0x7f1e970e08b3 in __libc_start_main (/lib64/libc.so.6+0x208b3)
    #28 0x418908 in _start (/home/jkt/work/prog/_build/sysrepo/GCC_6_ASAN-Debug/tests/sysrepocfg_test+0x418908)



0% tests passed, 1 tests failed out of 1

Total Test time (real) =   4.44 sec

The following tests FAILED:
         29 - sysrepocfg_test (Failed)
Errors while running CTest
```

**Comment by jktjkt** [comment]
OK,  I screwed up. `sr_val_set_str_data` is just for string data. I was actually lokking for `sr_set_item_str`.

**Comment by michalvasko** [comment]
Hi,
alright, seems good now (and yes, tests are a mess...), thanks.

Regards,
Michal

**Pull request merged**
