### PR TITLE
test case to verify solution of sysrepo issue #950

### PR DESCRIPTION
**Pull request by frimpler**
Hi,

as it has been discussed in https://github.com/sysrepo/sysrepo/issues/950, this pull requests delivers the test case which verifies the solution for it (see https://github.com/sysrepo/sysrepo/pull/951)

Regards,
Frank

### CODE REVIEW

**Comment by frimpler** [comment]
@michalvasko 
Hi Michal,

this pull request has some trouble to get verified with travis. Who can help here? The build didn't even start. As it seems, there's a problem with expired signatures. 
The last line of the log says:
`The command "if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash deploy/travis/install-libs.sh; fi" failed and exited with 100 during .`

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
it seems it was just some temporary problem, seems to work now. However, OSX test was executed and there is a problem with `sysrepoctl_test` because a part of it is uninstalling `ietf-interfaces`, which is no longer possible as your module has a dependency on it.

Regards,
Michal

**Comment by frimpler** [comment]
yes, I have noticed it just now. Working on it.

**Comment by frimpler** [comment]
@michalvasko 
Hi Michal,
test case is now ready (closed and reopened, because I was not at the office). Please have a look.

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
seems fine now, thanks, except for one thing, why did you turn logging off?

Regards,
Michal

**Comment by frimpler** [comment]
oh. It seems that slipped through.. Was not my intention (needed to switch it off in order to see debugger output).

**Comment by frimpler** [comment]
@michalvasko
Hi Michal,
as it seems, this pull request has not yet been merged. Any reasons for it?
Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
it was not merged because when I look at all the changes I still see logging turned off.

Regards,
Michal

**Comment by frimpler** [comment]
I'll open a new pull request: https://github.com/sysrepo/sysrepo/pull/983

**Pull request closed without merging**
