### PR TITLE
Save the commit context before sending notifications

### PR DESCRIPTION
**Pull request by alangefe**
This pull request corresponds to #1113 , which describes the problem and proposed solution. In summary, this request moves saving the commit context to before sending out commit notifications. This eliminates the window of time during which notified subscribers can query for the changes corresponding to the notification and get an error because the changes have not yet been saved.

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi Andrew,
it seems fine to me, thanks.

Regards,
Michal

**Comment by rosy8** [comment]
Hi,

In one of the scenario I got error like 
No NP commit context for commit ID ..

Is it related to this scenario ??

Regard's
Rosy

**Comment by michalvasko** [comment]
Hi Rosy,
I think this scenario could have happened to you (the error message is the same) but it also could have been caused by some other bug. If it continues to happen to you, please start another issue.

Regards,
Michal

**Comment by rosy8** [comment]
Hi Michal,

Ok. 
I will start a new thread for this issue.

Regard's
Rosy

**Pull request merged**
