### PR TITLE
String val

### PR DESCRIPTION
**Pull request by mislavn**
Implemented C++ methods for functions sr_set_item_str() and sr_val_to_str().

@rastislavszabo I am not sure what error message to return if I get NULL from sr_val_to_str().
Now it returns SR_ERR_OPERATION_FAILED.

Also would it be a problem to create a similar functions for nodes, something like sr_node_to_str().

### CODE REVIEW

**Comment by rastislavszabo** [comment]
>  I am not sure what error message to return if I get NULL from sr_val_to_str(). Now it returns SR_ERR_OPERATION_FAILED.

I'm not sure either. I actually started to think that `sr_val_to_str` should return an error code as the rest of the API functions... For now we can leave it as `SR_ERR_OPERATION_FAILED`.

**Comment by rastislavszabo** [comment]
> Also would it be a problem to create a similar functions for nodes

`sr_val_to_str` can be used also used for nodes, since nodes can be safely casted to `sr_val_t`. But we can create wrappers for `sr_node_t` type too.

**Comment by mislavn** [comment]
> sr_val_to_str can be used also used for nodes, since nodes can be safely casted to sr_val_t. But we can create wrappers for sr_node_t type too.

Thanks @rastislavszabo 

Also if it is not a problem, could you make a function like:
int string_to_val(sr_val_t **value, const char *xpath, const char *value);

The function would create a sr_val_t from the xpath and value.
This would be helpful with operational data.

**Comment by rastislavszabo** [comment]
@mislavn: it is `sr_val_set_xpath` + `sr_val_set_str_data`

**Comment by mislavn** [comment]
OK, thanks.

**Pull request merged**
