### PR TITLE
call lyd_validate after lyd_dup to rebuild leafref pointer

### PR DESCRIPTION
**Pull request by qmm161**

### CODE REVIEW

**Comment by qmm161** [comment]
I'm not very sure about this pull request too. The sysrepo code in my project was updated few weeks ago, and sysrepo get seg fault in sr_libyang_leaf_copy_value in case LY_TYPE_LEAFREF when recursive call sr_libyang_leaf_copy_value(this bug could not reproduce everytime), i find the bug was caused by lyd_dup when sysrepo call it to prepare prev_data_trees in commit context, so i reported an issue and libyang fixed that API... yesterday when i compare to newest sysrepo code on github, I find that the recursive calling of sr_libyang_leaf_copy_value was deleted , maybe i should try reproduce the bug with the newest sysrepo code some days later.

**Comment by lukasmacko** [comment]
Yes, it might be already fixed. Give it a try if you can reproduce it with the latest code.

**Comment by lukasmacko** [comment]
any update on this? can I close the pull request?

**Comment by rastislavszabo** [comment]
Closing this PR, as it is now completely out-of-sync with the current codebase.

**Pull request closed without merging**
