### PR TITLE
Versioning

### PR DESCRIPTION
**Pull request by rkrejci**

### CODE REVIEW

**Comment by rkrejci** [comment]
I'm afraid I'm not getting your point. What do you think is a problem here?

Anyway, rethinking the problem again - is it a good idea to have `SONAME` in this library? Its purpose is actually to allow to have multiple versions of the library installed in the system at once. But `libsysrepo.so` is used to communicate with `sysrepod` (or to access datastore). So having multiple (soname) versions of the library in the system can cause that a client using version X can try to communicate with the sysrepod version Y. Which may cause problems. Maybe we need some other mechanism for version checking, what do you think?

**Comment by antonio-paunovic** [comment]
Not exactly a problem, but it seems unconventional.

Rethinking the problem, you're right. `libsysrepo` is linked to sysrepod, sysrepocfg, etc. during the build. They will all use same version and I can't think of reason why would anybody want situation where parts of Sysrepo infrastructure (also plugin .so files) could have different versions.

**Comment by rkrejci** [comment]
Well, I can imagine that it can happen that plugins/connected apps (which are not part of the sysrepo project and built at different time) can be built with different version. But then the issue is not solved by SONAME, we will need a mechanism on the client side to detect this. 

I'm going to prepare something and will wait also for feedback in #788, but currently this pull request is not ready for merge.

**Comment by antonio-paunovic** [comment]
OK. Another thing I noticed is that libyang and this pull use major and minor version for SOVERSION and usually (like in `/usr/lib` on Linux) libs tend to only use major version for it. I can't find out why, since minor version also describes API.
This is what I meant by unconventional before. Maybe not very important difference at the moment.

So instead of:
`
set(SYSREPO_VERSION ${SYSREPO_MAJOR_VERSION}.${SYSREPO_MINOR_VERSION}.${SYSREPO_MICRO_VERSION})
set(SYSREPO_SOVERSION ${SYSREPO_MAJOR_VERSION}.${SYSREPO_MINOR_VERSION})
`

we would have: 
`
set(SYSREPO_VERSION ${SYSREPO_MAJOR_VERSION}.${SYSREPO_MINOR_VERSION}.${SYSREPO_MICRO_VERSION})
set(SYSREPO_SOVERSION ${SYSREPO_MAJOR_VERSION})
`

**Pull request closed without merging**
