### PR TITLE
test case to verify solution of sysrepo issue #1032

### PR DESCRIPTION
**Pull request by frimpler**
Hi,

as discussed in the mentioned issue, here's the test case to verify the solution. For the description of the test, please refer to https://github.com/sysrepo/sysrepo/issues/1032

Btw.: 
In order to get rid of the installed modules afterwards, I had to add an ugly workaround. I hope, you can live with it, as long as no solution for the uninstallation of interlocked modules is in sight.

Kind Regards,
Frank Rimpler

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi Frank,
actually, it is already possible to uninstall several modules at once using `sysrepocfg`. I have referenced the commit in #1032 but not mentioned it explicitly, sorry about that.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,

yes, I have already noticed it and tried to apply it, before I created the pull request, but it didn't work (in either un-installation order). Anyway, because my expectation was, that interlocked modules cannot be easily un-installed, I didn't undertake more investigations. Do you suggest any change in the test?

Regards,
Frank

**Comment by michalvasko** [comment]
Hi Frank,
just uninstall the modules with this command
```C
exec_shell_command("../src/sysrepoctl --uninstall --module mutual-leafref-base,mutual-leafref-augment", ".*", true, 0);
```
It worked fine for me. However, I have tried uninstalling first `mutual-leafref-augment` and that was not handled properly so I have created a pull request which should make the order arbitrary.

Regards,
Michal

**Comment by frimpler** [comment]
Hi Michal,

I'm lucky that un-installation works now. So please pull it in :-)

Regards,
Frank

**Pull request merged**
