### PR TITLE
add java package support

### PR DESCRIPTION
**Pull request by 9606**
### Description
Since most Java applications have packages, it is necessary to add packages to swig java extensions.

### Test case
Use the original test cases.

### CODE REVIEW

**Comment by mislavn** [comment]
Please can you wait with your pull request, I'm currently making some changes to the C++ bindings, where a "sysrepo" namespace will be introduced.
Something similar to https://github.com/CESNET/libyang/pull/586.

**Comment by mislavn** [comment]
You can rebase once my pull request is merged into master.

**Comment by mislavn** [comment]
Please wait for the pull request https://github.com/sysrepo/sysrepo/pull/1295.

**Comment by 9606** [comment]
@mislavn hello, is there any problem in this pull request?

**Comment by mislavn** [comment]
@9606 please can you make sure the Java unit tests are executed with ctest.
To generate unit tests you need to have `libcmocka` installed and to run Java unit tests use `ctest -R java -V`.

Please let me know if you encounter any issues, the Java bindings were not maintained for some time.

**Comment by 9606** [comment]
> @9606 please can you make sure the Java unit tests are executed with ctest.
> To generate unit tests you need to have `libcmocka` installed and to run Java unit tests use `ctest -R java -V`.
> 
> Please let me know if you encounter any issues, the Java bindings were not maintained for some time.

I am so sorry, ctest has no problem now.

**Comment by mislavn** [comment]
I have some issues with ctest and SWIG overload warning for uint8_t but I can fix it later.

@michalvasko do you approve the patch https://github.com/sysrepo/sysrepo/pull/1294/commits/0a540bcf06c8647e39cdf338d9308ebefd9abbe8.

**Comment by michalvasko** [comment]
@mislavn The situation it is supposed to fix has not happened to me but I can imagine it could. It is not the best solution but I am fine with it.

Regards,
Michla

**Pull request merged**
