### PR TITLE
Cpp event notif

### LINKED ISSUE #1057: Support for sr_event_notif_send for SWIG python
I see that the interface file does not have sr_event_notif_send support. How to send notifications using SWIG/Python2?

### PR DESCRIPTION
**Pull request by mislavn**
### Description
Implemented the function sr_event_notif_send and sr_event_notif_send_tree in the language bindings. Also mada small bug fixes.

### Closure
closes  #1057

### CODE REVIEW

**Comment by mislavn** [comment]
I'm not sure what should I do if the sr_event_notif_send function returns "SR_ERR_NOT_FOUND", at the moment an exception is thrown.

**Comment by michalvasko** [comment]
Why not? That is how errors are communicated in C++ and I do not think it is a valid situation, it is an error.

Regards,
Michal

**Comment by mislavn** [comment]
ok.

**Comment by jktjkt** [comment]
FYI, this looks like duplicating 9e31589366041ec188186762c08bda0ad880f09c. I'm not really attached to the API names I used, so feel free to clean this up by removing any of these :).

**Comment by mislavn** [comment]
Sorry, I haven't noticed them before.
I'll make a new pull request and remove send_event API to make it more consistent, thanks for the reminder.

**Pull request merged**
