### PR TITLE
docker FEATURE use libssh stable-0.9 branch in sysrepo-netopeer2 latest Dockerfile

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by michalvasko** [comment]
Okay, checking-out a specific version is a reasonable approach but then I would opt for the latest 0.9.5, no reason not to anymore (since it has finally fixed all the damn regression bugs).

**Comment by jsmolic** [comment]
@michalvasko Sure, that makes sense. I have added the appropriate changes

**Comment by jsmolic** [comment]
Let's actually use `stable-0.9` branch

**Comment by jsmolic** [comment]
Thanks

**Pull request merged**
