### PR TITLE
add default nodes into empty data trees if empty data can be validated.

### LINKED ISSUE #335: Top level default nodes & empty data tree
Currently only way how to add default nodes is validation function `lyd_validate`. That is one of the reasons why validation used to be done for all data trees loaded from file system, even empty ones.

However,  validation fails if module contains a top-level mandatory node and data tree is empty. see https://github.com/sysrepo/sysrepo/issues/333 As a result of bugfix validation is skipped and default nodes are not added if data tree is empty during file loading.

Default nodes are correctly added during validaition `sr_validate()` and commit `sr_commit()`.

The aim of this issue is to add default nodes into empty data trees.

### PR DESCRIPTION
**Pull request by fanchanghu**
Hi, 
This request is used to fix #335 only when empty data can be validated (now, even if the empty data can be validated, get-config with 'report-all' still returns empty).

### CODE REVIEW

**Comment by rastislavszabo** [comment]
Build fails due to https://github.com/CESNET/libyang/issues/222, waiting for fix in libyang.

**Comment by rastislavszabo** [comment]
The build now works. It seems that the tests are not passing with this fix, we will need to look into that.

**Comment by fanchanghu** [comment]
I  checked this problem, but I can not build success even if I revert my change. The error message like this:
```
-- Exec: /root/github/sysrepo/build/src/sysrepocfg --import=/root/github/sysrepo/examples/yang/ietf-interfaces.data.xml --datastore=startup --format=xml --level=0 ietf-interfaces
CMake Error at examples/cmake_install.cmake:79 (message):
  Error: 1
Call Stack (most recent call first):
  cmake_install.cmake:146 (INCLUDE)


make: *** [install] Error 1
```
what I do is like this:
1, update libyang and sysrepo to latest in branch master;
2, use `cmake .. && make install && make test` in libyang/build, it's OK;
3, use `cmake -DGEN_LANGUAGE_BINDINGS=0 .. && make install && make test` in sysrepo/build, and get the error. (If I do not use `-DGEN_LANGUAGE_BINDINGS=0`, some .cpp files failed to compile.)

**Comment by fanchanghu** [comment]
I changed 2 test cases according to the CI job log, hope it can work now...

**Comment by fanchanghu** [comment]
Hi,
I try to change some test cases to make them pass, however, I'm not sure it's OK to do it like that...
@rastislavszabo

**Pull request merged**
