### PR TITLE
notify subscribers of oper discard-items and remove redundant push data

### PR DESCRIPTION
**Pull request by irfanHaslanded**
Remove any "pushed" operational data matching the xpath of discard-items nodes from the mod_info->data.

This will allow creation of a diff reporting data being discarded.

Without this, discarded data are still present in the SHM, which is also not ideal.

For example:
cat /dev/shm/sr_ietf-interfaces.operational.1-1 | jq {
  "ietf-interfaces:interfaces-state": {
    "@": {
      "ietf-origin:origin": "ietf-origin:unknown"
    },
    "interface": [
      {
        "name": "eth1",
        "type": "iana-if-type:ethernetCsmacd"
      },
    ]
  },
  "sysrepo:discard-items": "/ietf-interfaces:interfaces-state/interface[name='eth1']"
}

Here, we see `eth1` data still present along with the discard-items.

This slows down reading from the operational datastore, which most likely happens far more frequently than writing to it.

With this change, operational data is simplified to cat /dev/shm/sr_ietf-interfaces.operational.1-1 | jq {
  "sysrepo:discard-items": "/ietf-interfaces:interfaces-state/interface[name='eth1']"
}

This will still not inform subscribers of changes to enabled data in the operational datastore.

### CODE REVIEW

**Comment by michalvasko** [comment]
I am not sure you understand what `discard-items` is supposed to do, have you read the [docs](https://netopeer.liberouter.org/doc/sysrepo/devel/html/push_oper_data.html)?

> Without this, discarded data are still present in the SHM, which is also not ideal.

The discarded data **are supposed to be present** in the SHM. The `discard-items` nodes essentially modify the data for the session, not the data of other sessions.

**Comment by irfanHaslanded** [comment]
You are right, this is still not clear to me in spite of reading the docs multiple times.

> Additionally, using [sr_discard_items()](https://netopeer.liberouter.org/doc/sysrepo/devel/html/group__edit__data__api.html#ga3c93aa25830a13af79add17e3269f9d4) an XPath can be set that will select all the nodes to be removed from previous data, which may be enabled running data or any push oper data with a lower order (higher priority).

>  an XPath can be set that will select all the nodes to be removed from previous data

1. I don't think it is clear _"when"_ this removal should happen, and more specifically _"why"_ should the removal not happen while writing to the operational datastore and only happen when operational data is read.

>  The discard-items nodes essentially modify the data for the session, not the data of other sessions.

2. This is completely the opposite of what I understood from reading the docs.

>  which may be enabled running data or any push oper data with a lower order (higher priority).

and 

> When building the operational datastore, all the stored push data are applied in a specific order. That means data for each session are loaded, previous items discarded (if any set), and then merged into the operational datastore. Using a combination of discarding items and merging data, it should be possible to fully customize the final operational datastore.

By _"previous items discarded"_, don't you mean data loaded until now from all sources (other push sessions and enabled data)?

**Comment by jktjkt** [comment]
The `operational` DS still works with *edits*, not with *content*. This is important because these edits are applied on top of some "previous data", and this "previous data" might change independently of your stored edit. For example, the very first layer of these data is the content of `running`. If you push a change which "discards" some previous data, you're storing an "intention to remove", which will make sure that this particular subtree will *never* make it past the current edit -- no matter whether the data are actually present in the previous content, or not.

The word "discard" is now, unfortunately, overridden for two completely different meanings in the public API. The `sr_discard_items` is used for the purpose of ensuring that the data from previous content will not be present after the current edit is applied. The `sr_discard_changes` or `sr_discard_changes_xpath` manipulates the edit of the current session.

>> The discard-items nodes essentially modify the data for the session, not the data of other sessions.
>
> This is completely the opposite of what I understood from reading the docs.

That explanation might be a bit misleading. I guess that what @michalvasko was saying is that these data *cannot* be physicaly removed from the SHM, in-place. The reason for that is that if the current session is closed, its edits must be undone. If the edit physically removed the data from SHM, these data would be gone now, and could not be restored. So the operation very much "modifies the final visible content of the operational DS", but it does that in a way which does *not* modify the stored data in-place.

**Comment by michalvasko** [comment]
> I don't think it is clear "when" this removal should happen, and more specifically "why" should the removal not happen while writing to the operational datastore and only happen when operational data is read.

I think the "when" is explained in detail in the first sentence you quoted. But if you have ideas for improving the docs, please share them so it can be improved. My rationale for not reporting any changes to subscribers for `discard-items` nodes is that only the changes of the data pushed by the session are reported. Since the data of other sessions/enabled running data are discarded, these are not reported.

The removed data **at the moment** the `discard-items` are pushed could be reported but the downside is that the actually discarded data can change in time without the push oper data of the session changing. But since there is no perfect solution, I have no problem with this change.

> This is completely the opposite of what I understood from reading the docs.

We are disagreeing on irrelevant terms. What I simply meant is that the `discard-items` node is stored in the data of the session but yes, it is essentially applied on data of other sessions/enabled running data.

> By "previous items discarded", don't you mean data loaded until now from all sources (other push sessions and enabled data)?

Yes, that is what it means.

**Comment by irfanHaslanded** [comment]
Thanks @michalvasko  and @jktjkt for the detailed explanation.

>That explanation might be a bit misleading. I guess that what @michalvasko was saying is that these data cannot be physicaly removed from the SHM, in-place. The reason for that is that if the current session is closed, its edits must be undone. If the edit physically removed the data from SHM, these data would be gone now, and could not be restored. So the operation very much "modifies the final visible content of the operational DS", but it does that in a way which does not modify the stored data in-place.

I will think more on this and how it affects us.

**Comment by irfanHaslanded** [comment]
@michalvasko @jktjkt 

> The word "discard" is now, unfortunately, overridden for two completely different meanings in the public API. The sr_discard_items is used for the purpose of ensuring that the data from previous content will not be present after the current edit is applied. The sr_discard_changes or sr_discard_changes_xpath manipulates the edit of the current session.

To make the intention and result of calling the functions very clear, is it possible to rename them to accurately reflect what they do

`sr_discard_changes()` -> `sr_erase_staged()` : Erase indicates that it is irreversible. Staged indicating that the changes are not yet committed.
`sr_discard_changes_xpath()` -> `sr_erase_staged_xpath()` 
`sr_discard_oper_changes()` -> `sr_erase_oper_pushed()`

And keep only `sr_discard_items` with discard in name.

**Comment by michalvasko** [comment]
I do not think the naming confusion is such a major concern. Also, as discussed with @jktjkt I would prefer to avoid renaming functions right now and increasing the major SO version. Please focus on the functionality.

**Comment by jktjkt** [comment]
In the C++ bindings, we used the phrase "drop foreign operational content" for `sr_discard_items`. Maybe an even better word might be "block" because that (hopefully) shows that the data are "still somewhere", but they are "not propagated any further". I'm not a native speaker, though. The important port is IMHO not whether we call this "erase", "drop" or "discard", but to ensure that we do not use the very same phrase to refer to multiple different things, which is why I dislike @irfanHaslanded 's proposal with the word "erase" used for everything.

IMO, given the huge difference in semantics, calling this API break an API break and bumping the SOVERSION is the obvious thing to do, but it seems that the maintainer disagrees.

**Comment by irfanHaslanded** [comment]
Sure, I hope renaming will be considered at the time of next major version bump, whenever that happens.

> The removed data at the moment the discard-items are pushed could be reported but the downside is that the actually discarded data can change in time without the push oper data of the session changing. But since there is no perfect solution, I have no problem with this change.

@michalvasko So, Is the functionality change this PR brings okay?

**Comment by michalvasko** [comment]
The idea is fine, like I said, but I do not really like the implementation. There seems to be a lot of (new) code and not called at the place I would expect it to so I will implement it myself.

**Comment by michalvasko** [comment]
Actually, this is a much bigger change than assumed. Currently, the changes in push oper data of a session are reported only compared to the previous push oper data of the session (why `discard-items` is not reported at all). With this change the diff will have to be created by comparing the whole operational DS with the previous push oper data of the session and with the new push oper data.

In other words, while now only the push oper data of the session need to be loaded, it will be required to build the whole operational DS twice and then compare them.

Like I said, I have no problem with this but the performance consequences are obvious, so are you fine with this @irfanHaslanded?

**Comment by irfanHaslanded** [comment]
Yes, I am fine with the performance consequence, given that not reporting changed operational datastore to subscribers (because of discarded operational data) is not an option for us.

**Comment by jktjkt** [comment]
Same here -- as a subscriber, what I'm interested in is the "final state" of the operational DS. From a subscriber's PoV, it is not important *what* caused a change, but it's definitely a bug if I'm not notified about "a visible change" in the DS content.

**Comment by michalvasko** [comment]
That is all fine in theory but in practice it is more complex than that. What about oper data get subscriptions? What would you expect?
```
enabled running data + stored oper push data + session OLD oper push data + oper get subscriptions data
   ^
  diff (reported changes)
   v
enabled running data + stored oper push data + session NEW oper push data + oper get subscriptions data
```
or without `oper get subscriptions data`? I would prefer without them because with them seems like an overkill, not just regarding the performance. But, if you insist on "being notified about every visible change" accurately (at least at that particular moment), they need to be included, too.

**Comment by michalvasko** [comment]
Actually, the better choices would probably be
```
enabled running data + lower-priority stored oper push data + session OLD oper push data + higher-priority stored oper push data + oper get subscriptions data
   ^
  diff (reported changes)
   v
enabled running data + lower-priority stored oper push data + session NEW oper push data + higher-priority stored oper push data + oper get subscriptions data
```
vs
```
enabled running data + lower-priority stored oper push data + session OLD oper push data
   ^
  diff (reported changes)
   v
enabled running data + lower-priority stored oper push data + session NEW oper push data
```
The difference is that the former reports fully accurate changes in the oper DS data while the latter reports `discard-changes` accurately and just changes in the push oper data of the session (which may not be accurate or even be none in the final oper DS).

Thoughts? @jktjkt @irfanHaslanded

**Comment by irfanHaslanded** [comment]
I don't think changes in "oper get" data can ever be properly notified, as this usually contains frequently changing data (for example interface statistics) and the system design expects this. So any notification is likely to be outdated.

So, IMHO, we should be fine not notifying "oper get" data changes, even if they are blocked due to some pushed data / configuration.

**Comment by irfanHaslanded** [comment]
Will considering "enabled running data" make locking more complex (meaning reading from operational datastore/ writing to operational datastore) needing locks on Running data and change_sub?

**Comment by michalvasko** [comment]
Naturally, the relevant `running` data needs to be normally loaded as the first step, from which only the enabled data are then selected.

**Comment by irfanHaslanded** [comment]
I think we should skip `"enabled running data"`, due to the fact that we will need to hold a lot more locks and for a lot more time, which I am afraid will cause deadlocks and increased lock contention and IMHO degraded overall performance.

Prior to v3.x, we did not get notified of changes to this either, So, it should be okay, I think.

**Comment by michalvasko** [comment]
Okay, I suppose, even though I think you are too focused on your specific use-case and ignore any other possible requirements. The degraded performance was my initial argument which you dismissed back then.

**Comment by michalvasko** [comment]
Took quite some effort but should be implemented and working.

**Pull request closed without merging**
