### PR TITLE
add sr_set_diff_check_callback testcases for connection and session

### PR DESCRIPTION
**Pull request by fredgan**
This is only a part of testcase for  issue #1931 .I will add other testcases for connection and session later.

### CODE REVIEW

**Comment by michalvasko** [comment]
Hi Fred,
I see what you tried to do but there are a few problems. Generally, I would like to avoid calling `system()` but that is not really the problem. To add users, you would need to run this test as `root` and that should be avoided if possible. However, you only need 2 users for the test. You can use the user of the process and then just take another arbitrary one from the system. That should not be a problem using the functions for traversing all the users on a system.

That way both requiring `root` access and modifying the users on the system would be avoided.

Regards,
Michal

**Comment by michalvasko** [comment]
Okay, the test passed now but what about the name `connection_and_session`? It is quite vague and I am also not sure it covers the actual test. Do you plan to add any more, what exactly will they test?

Regards,
Michal

**Comment by fredgan** [comment]
@michalvasko 

Hi Michal,
Do you have any suggestions or tips for the form of the testcases? Which part should be key module that we should focus on. In fact, now I am not quite sure whether I am in the right direction.

**Comment by michalvasko** [comment]
Hi,
well, you see that even this test initially failed so I have no problem with it in general. However, what is mostly needed are use-cases of functions that allow large number of different uses, made even more if they are combined.

One such (family of) function is `sr_set_item_str()` because its behavior depend on any already existing changes in the session. But there are not that many cases and I think they should be fairly well covered by now. You can still take a look and I am certain you can come up with new use-cases and perhaps even some non-working ones.

The worst in this aspect are subscriptions. You can have as many of them as you want, they are combined to communicate using a single shared memory if they operate on the same module, and there are even priorities and callback failures (abort events) to worry about. This is a huge number of possibilities that can never be exhaustively tested. My approach was to test the cases I could think of and though potentially problematic while adding any new ones discovered in the issues. So, you can definitely add more of these and recently even a `test_process` was added that includes a basic infrastructure for testing running several *sysrepo* processes at once. That can be additionally used to test concurrency.

But I was only talking about change subscriptions. You can add operational ones that add another layer of complexity and are complicated even on their own because they allow nesting or overlapping.

Note that to come up with reasonable test cases for these mechanisms, you need an in-depth understanding of them. So starting with simpler tests and slowly making them more complex is probably the way to go. Also, any feedback regarding the documentation is as important as actual tests. Meaning please report any behavior you had to learn on your own and could be documented in a few sentences instead.

Regards,
Michal

**Comment by fredgan** [comment]
Hi Michal, Thanks for your tips. I will take them consider.

**Pull request closed without merging**
